'''
PeerNet++ JSON Handler
======================
Parse JSON-formatted paper data for import.

Supported Formats:
- OpenAlex JSON export
- Custom PeerNet++ JSON format
- Generic paper metadata JSON

Converts to standardized paper dict for intake.
'''

import json
from typing import Dict, Optional
import logging

logger = logging.getLogger(__name__)

class JSONHandler:
    @staticmethod
    def parse_paper_json(json_data: str) -> Optional[Dict]:
        """
        Parse JSON string or dict into paper data format.
        Expects OpenAlex-compatible format.
        """
        try:
            if isinstance(json_data, str):
                data = json.loads(json_data)
            elif isinstance(json_data, dict):
                data = json_data
            else:
                raise ValueError("Input must be JSON string or dict")

            # Generate paper_id if missing
            import uuid
            paper_id = data.get('id', data.get('paper_id', ''))
            if not paper_id:
                # Generate from title or use UUID
                title = data.get('title', '')
                if title:
                    # Create ID from title (first 50 chars, lowercased, replace spaces)
                    paper_id = 'json_' + title[:50].lower().replace(' ', '_').replace(',', '').replace('.', '')
                else:
                    paper_id = f'json_{uuid.uuid4().hex[:12]}'
                logger.info(f"Generated paper_id: {paper_id}")

            # Normalize to our internal format
            paper_data = {
                'paper_id': paper_id,
                'title': data.get('title', ''),
                'authors': data.get('authors', []),
                'year': str(data.get('year', data.get('publication_year', ''))),
                'abstract': data.get('abstract', ''),
                'doi': data.get('doi', ''),
                'full_text': data.get('full_text', ''),
                'sections': data.get('sections', {}),
                'keywords': data.get('keywords', []),
                'source': 'json'
            }

            # Clean up paper_id if it's a full URL
            if paper_data['paper_id'].startswith('https://openalex.org/'):
                paper_data['paper_id'] = paper_data['paper_id'].replace('https://openalex.org/', '')

            return paper_data

        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON format: {str(e)}")
            return None
        except Exception as e:
            logger.error(f"Error parsing JSON data: {str(e)}")
            return None

    @staticmethod
    def validate_paper_data(paper_data: Dict) -> bool:
        """
        Validate that paper data has required fields.
        """
        # Only require title, paper_id is auto-generated if missing
        required_fields = ['title']
        for field in required_fields:
            if not paper_data.get(field):
                logger.error(f"Missing required field: {field}")
                return False
        
        # Ensure paper_id exists (should be generated by parse_paper_json)
        if not paper_data.get('paper_id'):
            logger.error("paper_id was not generated properly")
            return False
            
        logger.info(f"Validated paper data: {paper_data.get('title')} (ID: {paper_data.get('paper_id')})")
        return True
