from typing import List, Dict, Any
import logging
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from models.papers import Paper
from models.reviews import Review
from models.consensus import Consensus
from models.bias_flags import BiasFlag
from models.custom_reviewers import CustomReviewer
from models.ledger_blocks import LedgerBlock
from agents.reviewer_agent import ReviewerAgent
from agents.consensus_agent import ConsensusAgent
from agents.bias_detection_agent import BiasDetectionAgent
from agents.plagiarism_agent import PlagiarismAgent
from extensions import socketio
from config import Config

logger = logging.getLogger(__name__)

class ReviewSimulation:
    def __init__(self):
        self.min_reviewers = Config.MIN_REVIEWERS
        self.max_reviewers = Config.MAX_REVIEWERS

    def simulate_paper_review(self, paper: Paper, num_reviewers: int = None, custom_reviewer_ids: List[str] = None) -> Dict[str, Any]:
        """
        Run the complete review simulation for a single paper.
        """
        logger.info("Starting review simulation for paper: %s", paper.title)
        user_id = str(paper.user_id) if hasattr(paper, 'user_id') and paper.user_id else None
        
        socketio.emit('review_progress', {
            'paper_id': paper.paper_id,
            'status': 'starting',
            'message': f"Starting review for '{paper.title[:30]}...'"
        }, room=user_id)
        socketio.sleep(0.1)

        # Step 1: Assign reviewers
        if custom_reviewer_ids:
            reviewers = self._create_reviewers_from_custom(custom_reviewer_ids)
        else:
            count = self._determine_reviewer_count(num_reviewers)
            reviewers = self._create_reviewers(count)

        # Step 2: Generate reviews
        reviews_data = []
        for reviewer in reviewers:
            socketio.emit('review_progress', {
                'paper_id': paper.paper_id,
                'status': 'reviewing',
                'message': f"Agent {reviewer.agent_id} is generating a review..."
            }, room=user_id)
            socketio.sleep(0.1)
            try:
                paper_dict = paper.to_dict()
                # Ensure required fields are not None
                if not paper_dict.get('title'):
                    paper_dict['title'] = 'Unknown Title'
                if not paper_dict.get('abstract'):
                    paper_dict['abstract'] = 'No abstract available'
                
                review_result = reviewer.process({'paper': paper_dict})
                reviews_data.append(review_result)
                logger.info(f"Review generated by {reviewer.agent_id}")
            except Exception as e:
                logger.error("Error generating review by %s: %s", reviewer.agent_id, str(e))
                # Create a fallback review to prevent total failure
                fallback_review = {
                    'reviewer_id': reviewer.agent_id,
                    'scores': {
                        'novelty': 6.0,
                        'clarity': 6.0,
                        'methodology': 6.0,
                        'relevance': 6.0,
                        'overall': 6.0
                    },
                    'written_feedback': f'Review could not be completed due to technical issues. Default assessment provided by {reviewer.agent_id}.',
                    'confidence': 0.5,
                    'logs': f'Fallback review generated due to error: {str(e)}'
                }
                reviews_data.append(fallback_review)
                continue

            # Save review to database
            try:
                review = Review(
                    paper=paper,
                    reviewer_id=review_result['reviewer_id'],
                    scores=review_result['scores'],
                    written_feedback=review_result['written_feedback'],
                    confidence=review_result['confidence'],
                    logs=review_result['logs']
                )
                review.save()
            except Exception as e:
                logger.error(f"Error saving review: {str(e)}")
                continue

            # Log to ledger
            try:
                self._log_to_ledger(paper, 'review_generated', {
                    'reviewer_id': review_result['reviewer_id'],
                    'scores': review_result['scores']
                })
            except Exception as e:
                logger.error("Failed to log review to ledger: %s", str(e))

        # Step 3: Run consensus (only if we have reviews)
        if not reviews_data:
            logger.error("No reviews generated, cannot proceed with consensus")
            return {
                'paper_id': paper.paper_id,
                'reviews_count': 0,
                'consensus_decision': 'Failed - No Reviews',
                'bias_flags_count': 0,
                'status': 'failed'
            }
        
        socketio.emit('review_progress', {
            'paper_id': paper.paper_id,
            'status': 'consensus',
            'message': 'Building consensus from reviews...'
        }, room=user_id)
        
        # Run consensus with error handling
        consensus_result = {'decision': 'Error', 'negotiation_rounds': 0, 'final_scores': {}, 'confidence': 0.0}
        try:
            consensus_agent = ConsensusAgent('consensus_001')
            consensus_result = consensus_agent.process({
                'reviews': reviews_data,
                'paper': paper.to_dict()
            })
            logger.info(f"Consensus reached: {consensus_result['decision']}")
        except Exception as e:
            logger.error(f"Error in consensus: {str(e)}")
            consensus_result = {
                'decision': 'Needs Revision',
                'negotiation_rounds': 1,
                'final_scores': {'overall': 6.5},
                'confidence': 0.5
            }

        # Save consensus to database
        consensus = Consensus(
            paper=paper,
            decision=consensus_result['decision'],
            negotiation_rounds=consensus_result['negotiation_rounds'],
            final_scores=consensus_result['final_scores'],
            confidence=consensus_result['confidence'],
            overall_explanation=consensus_result.get('overall_explanation', '')
        )
        consensus.save()

        # Log consensus to ledger
        try:
            self._log_to_ledger(paper, 'consensus_reached', {
                'decision': consensus_result['decision'],
                'final_scores': consensus_result['final_scores']
            })
        except Exception as e:
            logger.error("Failed to log consensus to ledger: %s", str(e))

        socketio.emit('review_progress', {
            'paper_id': paper.paper_id,
            'status': 'plagiarism_check',
            'message': 'Checking for plagiarism...'
        }, room=user_id)

        # Step 4: Run plagiarism detection (if enabled/needed)
        plagiarism_result = {'plagiarism_score': 0.0, 'similarity_matches': [], 'recommendations': [], 'analysis_summary': 'No plagiarism check performed.'}
        try:
            # Note: For a real system, comparison_papers would come from a database/corpus
            # For this simulation, we'll pass an empty list or a few dummy papers
            plagiarism_agent = PlagiarismAgent('plagiarism_001')
            plagiarism_result = plagiarism_agent.process({
                'paper': paper.to_dict(),
                'comparison_papers': [] # Placeholder: In a real system, fetch relevant papers
            })
            logger.info(f"Plagiarism detection completed. Score: {plagiarism_result['plagiarism_score']}")
        except Exception as e:
            logger.error(f"Error in plagiarism detection: {str(e)}")
            plagiarism_result = {
                'plagiarism_score': 0.0,
                'similarity_matches': [],
                'recommendations': [f"Plagiarism check failed: {str(e)}"],
                'analysis_summary': f"Plagiarism detection failed: {str(e)}"
            }

        # Log plagiarism detection to ledger
        try:
            self._log_to_ledger(paper, 'plagiarism_detected', {
                'plagiarism_score': plagiarism_result['plagiarism_score'],
                'summary': plagiarism_result['analysis_summary']
            })
        except Exception as e:
            logger.error("Failed to log plagiarism detection to ledger: %s", str(e))

        socketio.emit('review_progress', {
            'paper_id': paper.paper_id,
            'status': 'bias_check',
            'message': 'Detecting potential biases...'
        }, room=user_id)

        # Step 4: Run bias detection with error handling
        bias_result = {'bias_flags': [], 'total_flags': 0}
        try:
            bias_agent = BiasDetectionAgent('bias_001')
            bias_result = bias_agent.process({
                'reviews': reviews_data,
                'paper': paper.to_dict()
            })
            logger.info(f"Bias detection completed: {bias_result['total_flags']} flags found")
        except Exception as e:
            logger.error(f"Error in bias detection: {str(e)}")
            bias_result = {'bias_flags': [], 'total_flags': 0}

        # Save bias flags to database with error handling
        try:
            for flag in bias_result.get('bias_flags', []):
                try:
                    bias_flag = BiasFlag(
                        paper=paper,
                        flag_type=flag.get('flag_type', 'unknown'),
                        evidence=flag.get('evidence', {}),
                        confidence=flag.get('confidence', 0.5)
                    )
                    bias_flag.save()
                except Exception as e:
                    logger.error(f"Error saving bias flag: {str(e)}")
                    continue
        except Exception as e:
            logger.error(f"Error processing bias flags: {str(e)}")

        # Log bias detection to ledger
        try:
            self._log_to_ledger(paper, 'bias_detected', {
                'total_flags': bias_result.get('total_flags', 0),
                'flag_types': [f.get('flag_type', 'unknown') for f in bias_result.get('bias_flags', [])]
            })
        except Exception as e:
            logger.error("Failed to log bias detection to ledger: %s", str(e))

        # Update paper status based on consensus
        try:
            decision = consensus_result.get('decision', 'Needs Revision')
            if decision == 'Accept':
                paper.status = 'accepted'
            elif decision == 'Reject':
                paper.status = 'rejected'
            else:
                paper.status = 'needs_revision'
            paper.save()
        except Exception as e:
            logger.error(f"Error updating paper status: {str(e)}")

        socketio.emit('review_progress', {
            'paper_id': paper.paper_id,
            'status': 'completed',
            'message': f"Review complete! Final decision: {decision}"
        }, room=user_id)
        socketio.sleep(0.1)

        # Ensure we always return a valid result
        try:
            result = {
                'paper_id': paper.paper_id,
                'reviews_count': len(reviews_data),
                'consensus_decision': consensus_result.get('decision', 'Unknown'),
                'plagiarism_score': plagiarism_result['plagiarism_score'],
                'bias_flags_count': bias_result.get('total_flags', 0),
                'status': 'completed'
            }
        except Exception as e:
            logger.error(f"Error creating result: {str(e)}")
            result = {
                'paper_id': getattr(paper, 'paper_id', 'unknown'),
                'reviews_count': len(reviews_data),
                'consensus_decision': 'Error',
                'plagiarism_score': 0.0,
                'bias_flags_count': 0,
                'status': 'completed_with_errors'
            }

        logger.info("Review simulation completed for paper: %s", getattr(paper, 'title', 'Unknown'))
        return result

    def simulate_batch_review(self, papers: List[Paper]) -> List[Dict[str, Any]]:
        """
        Run review simulation for a batch of papers.
        """
        results = []
        for paper in papers:
            result = self.simulate_paper_review(paper)
            results.append(result)
        return results

    def _determine_reviewer_count(self, num_reviewers: int = None) -> int:
        """Determine number of reviewers (between min and max)."""
        import random
        if num_reviewers and self.min_reviewers <= num_reviewers <= self.max_reviewers:
            return num_reviewers
        else:
            return random.randint(self.min_reviewers, self.max_reviewers)

    def _get_default_reviewer_profiles(self) -> Dict[str, Dict[str, Any]]:
        """Get default reviewer profiles."""
        return {
            'dr_methodology': {'id': 'dr_methodology', 'expertise': ['methodology', 'statistics', 'experimental_design'], 'bias': 'strict_methodology'},
            'prof_novelty': {'id': 'prof_novelty', 'expertise': ['innovation', 'novelty', 'creativity'], 'bias': 'novelty_focused'},
            'dr_clarity': {'id': 'dr_clarity', 'expertise': ['writing', 'communication', 'clarity'], 'bias': 'clarity_focused'},
            'prof_theory': {'id': 'prof_theory', 'expertise': ['theory', 'foundations', 'concepts'], 'bias': 'theory_heavy'},
            'dr_practical': {'id': 'dr_practical', 'expertise': ['applications', 'industry', 'practical'], 'bias': 'application_focused'}
        }

    def _create_reviewers(self, count: int) -> List[ReviewerAgent]:
        """Create diverse reviewer agents with different expertise."""
        reviewer_profiles = self._get_default_reviewer_profiles()
        reviewer_list = list(reviewer_profiles.values())
        
        reviewers = []
        for i in range(count):
            profile = reviewer_list[i % len(reviewer_list)]
            reviewer = ReviewerAgent(
                agent_id=f"{profile['id']}_{i+1}",
                expertise=profile['expertise'],
                review_bias=profile['bias']
            )
            reviewers.append(reviewer)
        return reviewers

    def _create_reviewers_from_custom(self, reviewer_ids: List[str]) -> List[ReviewerAgent]:
        """Create reviewer agents from user-defined custom reviewers or default profiles."""
        from bson.objectid import ObjectId, InvalidId

        reviewers = []
        
        # Separate IDs into custom (ObjectId) and default (string starting with 'default_')
        custom_oid_list = []
        default_id_list = []
        for rid in reviewer_ids:
            if str(rid).startswith('default_'):
                default_id_list.append(rid)
            else:
                try:
                    custom_oid_list.append(ObjectId(rid))
                except (InvalidId, ValueError):
                    logger.warning(f"Invalid reviewer ID format: {rid}")
                    continue

        # Create agents from custom reviewers
        if custom_oid_list:
            custom_reviewers = CustomReviewer.objects(id__in=custom_oid_list)
            for i, custom_reviewer in enumerate(custom_reviewers):
                bias_map = {
                    'methodology': 'strict_methodology', 'novelty': 'novelty_focused',
                    'clarity': 'clarity_focused', 'theory': 'theory_heavy',
                    'application': 'application_focused'
                }
                review_bias = bias_map.get(custom_reviewer.expertise, 'balanced')
                
                # Use personality traits from custom reviewer to create more nuanced agent
                agent = ReviewerAgent(
                    agent_id=f"{custom_reviewer.name.replace(' ', '_')}_{i+1}",
                    expertise=[custom_reviewer.expertise],
                    review_bias=review_bias,
                    personality_traits={
                        'strictness': custom_reviewer.strictness,
                        'detail_focus': custom_reviewer.detail_focus,
                        'innovation_bias': custom_reviewer.innovation_bias,
                        'writing_standards': custom_reviewer.writing_standards,
                        'methodology_rigor': custom_reviewer.methodology_rigor,
                        'optimism': custom_reviewer.optimism
                    }
                )
                reviewers.append(agent)
                logger.info(f"Created custom reviewer agent: {agent.agent_id}")

        # Create agents from default profiles
        if default_id_list:
            default_profiles = self._get_default_reviewer_profiles()
            
            # Map frontend IDs to backend profile keys
            id_mapping = {
                'default_methodology': 'dr_methodology',
                'default_novelty': 'prof_novelty',
                'default_clarity': 'dr_clarity',
                'default_theory': 'prof_theory',
                'default_application': 'dr_practical',
                'default_balanced1': 'dr_methodology',
                'default_balanced2': 'prof_novelty'
            }
            
            for i, profile_id in enumerate(default_id_list):
                # Map the frontend ID to backend profile key
                profile_key = id_mapping.get(profile_id)
                
                if profile_key:
                    profile = default_profiles.get(profile_key)
                    if profile:
                        agent = ReviewerAgent(
                            agent_id=f"{profile['id']}_{len(reviewers) + i + 1}",
                            expertise=profile['expertise'],
                            review_bias=profile['bias']
                        )
                        reviewers.append(agent)
                        logger.info(f"Created default reviewer agent: {agent.agent_id}")
                    else:
                        logger.warning(f"Profile key not found: {profile_key}")
                else:
                    logger.warning(f"Unknown default profile ID: {profile_id}")

        if not reviewers:
            logger.warning("No valid reviewers found for IDs, falling back to default.")
            return self._create_reviewers(self.min_reviewers)

        return reviewers

    def _log_to_ledger(self, paper: Paper, event_type: str, data: Dict[str, Any]):
        """
        Log an event to the blockchain-style ledger.
        """
        # Get the last ledger block for this paper to get previous hash
        last_block = LedgerBlock.objects(paper=paper).order_by('-timestamp').first()
        previous_hash = last_block.hash if last_block else '0' * 64

        # Create new ledger block
        ledger_block = LedgerBlock(
            paper=paper,
            previous_hash=previous_hash,
            data={
                'event_type': event_type,
                'event_data': data
            }
        )
        ledger_block.save()
